### ISSUE TITLE
literally anyone could delete this fork.

### ISSUE THREAD

**Issue by zoey-on-github** [CodeLikeCrazE/modchat-preserved#101]
![image](https://user-images.githubusercontent.com/88806187/199394927-d3a5fda0-400e-4288-8cbd-9b13de44f728.png)
if you use refined github like i do, you dont even have to do the whole "digging through settings" song and dance.

please fix your repo permissions, i was this close to deleting this just because it would be funny asf

**Comment by CodeLikeCrazE** [comment]
wait what im dumb

**Comment by CodeLikeCrazE** [comment]
how does one fix this

**Comment by CodeLikeCrazE** [comment]
closed
